apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-deployment
spec:
  replicas: 3  # 컨테이너 3개로 구성
  selector:
    matchLabels:
      app: springapp  # matchLabels는 Service의 selector와 일치해야 합니다.
  template:
    metadata:
      labels:
        app: springapp  # Pod의 라벨이 Service와 매칭되어야 합니다.
    spec:
      containers:
        - name: springapp-container
          image: suzyhw96/springapp:1.0
          ports:
            - containerPort: 8999  # 컨테이너 내부에서 리스닝하는 포트
---
apiVersion: v1
kind: Service
metadata:
  name: springapp-service
spec:
  selector:
    app: springapp  # Deployment의 matchLabels와 일치해야 합니다.
  ports:
    - protocol: TCP
      port: 80  # 클러스터 외부에서 접근하는 포트
      targetPort: 8999  # 컨테이너 내부 포트
  type: LoadBalancer
